## 态密度

In [8]:
file1 = open("new0.dat",'r')
all_data = file1.read()    #全部读取进来，打印跟文本的形式的形似一样。all_data = file1.readlines()是做一个大列表，每一行代表列表中的一个元素。
print(all_data.split("\n"))  # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割

['     -26.655            0', '    -26.5407            0', '    -26.4264            0', '    -26.3122            0', '    -26.1979            0', '    -26.0837            0', '    -25.9694            0', '    -25.8552            0', '    -25.7409            0', '    -25.6267            0', '    -25.5124            0', '    -25.3982            0', '    -25.2839            0', '    -25.1697            0', '    -25.0554            0', '    -24.9411            0', '    -24.8269            0', '    -24.7126            0', '    -24.5984       0.0001', '    -24.4841       0.0006', '    -24.3699       0.0006', '    -24.2556        0.001', '    -24.1414       0.0012', '    -24.0271       0.0014', '    -23.9129       0.0016', '    -23.7986       0.0016', '    -23.6843       0.0017', '    -23.5701       0.0017', '    -23.4558       0.0017', '    -23.3416       0.0017', '    -23.2273       0.0009', '    -23.1131       0.0002', '    -22.9988            0', '    -22.8846            0', '    -22.7703

In [9]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
for i in all_data_dos:
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		print(i) 


     -26.655            0
    -26.5407            0
    -26.4264            0
    -26.3122            0
    -26.1979            0
    -26.0837            0
    -25.9694            0
    -25.8552            0
    -25.7409            0
    -25.6267            0
    -25.5124            0
    -25.3982            0
    -25.2839            0
    -25.1697            0
    -25.0554            0
    -24.9411            0
    -24.8269            0
    -24.7126            0
    -24.5984       0.0001
    -24.4841       0.0006
    -24.3699       0.0006
    -24.2556        0.001
    -24.1414       0.0012
    -24.0271       0.0014
    -23.9129       0.0016
    -23.7986       0.0016
    -23.6843       0.0017
    -23.5701       0.0017
    -23.4558       0.0017
    -23.3416       0.0017
    -23.2273       0.0009
    -23.1131       0.0002
    -22.9988            0
    -22.8846            0
    -22.7703            0
    -22.6561            0
    -22.5418            0
    -22.4276            0
    -22.3133

**把一个i数据按照每行进行切割,一个i数据转换成一个list，数据的每行是一个元素**    


In [10]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
for i in all_data_dos:
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		print(i.split("\n")) 


['     -26.655            0', '    -26.5407            0', '    -26.4264            0', '    -26.3122            0', '    -26.1979            0', '    -26.0837            0', '    -25.9694            0', '    -25.8552            0', '    -25.7409            0', '    -25.6267            0', '    -25.5124            0', '    -25.3982            0', '    -25.2839            0', '    -25.1697            0', '    -25.0554            0', '    -24.9411            0', '    -24.8269            0', '    -24.7126            0', '    -24.5984       0.0001', '    -24.4841       0.0006', '    -24.3699       0.0006', '    -24.2556        0.001', '    -24.1414       0.0012', '    -24.0271       0.0014', '    -23.9129       0.0016', '    -23.7986       0.0016', '    -23.6843       0.0017', '    -23.5701       0.0017', '    -23.4558       0.0017', '    -23.3416       0.0017', '    -23.2273       0.0009', '    -23.1131       0.0002', '    -22.9988            0', '    -22.8846            0', '    -22.7703

**对每条线，每一个数据点进行迭代，一个大列表。然后以空格的方法进行切割,这样就每个数据点切割成 能量和后面的状态数。**      
**在用map方法，把每个列表str转化成float**

In [11]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
for i in all_data_dos:
	each_line=[]  #新建空的列表存放每一行的数据
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		lines = i.split("\n") #
		for line in lines:    #对每条线，每一个数据点进行迭代，一个大列表。
			print(list(map(float,line.split())))     #以空格的方法进行切割,这样就每个数据点切割成 能量和后面的状态数。#在用list(map(float,列表_含有字符串)) 转化成浮点数
	

[-26.655, 0.0]
[-26.5407, 0.0]
[-26.4264, 0.0]
[-26.3122, 0.0]
[-26.1979, 0.0]
[-26.0837, 0.0]
[-25.9694, 0.0]
[-25.8552, 0.0]
[-25.7409, 0.0]
[-25.6267, 0.0]
[-25.5124, 0.0]
[-25.3982, 0.0]
[-25.2839, 0.0]
[-25.1697, 0.0]
[-25.0554, 0.0]
[-24.9411, 0.0]
[-24.8269, 0.0]
[-24.7126, 0.0]
[-24.5984, 0.0001]
[-24.4841, 0.0006]
[-24.3699, 0.0006]
[-24.2556, 0.001]
[-24.1414, 0.0012]
[-24.0271, 0.0014]
[-23.9129, 0.0016]
[-23.7986, 0.0016]
[-23.6843, 0.0017]
[-23.5701, 0.0017]
[-23.4558, 0.0017]
[-23.3416, 0.0017]
[-23.2273, 0.0009]
[-23.1131, 0.0002]
[-22.9988, 0.0]
[-22.8846, 0.0]
[-22.7703, 0.0]
[-22.6561, 0.0]
[-22.5418, 0.0]
[-22.4276, 0.0]
[-22.3133, 0.0]
[-22.199, 0.0]
[-22.0848, 0.0]
[-21.9705, 0.0]
[-21.8563, 0.0]
[-21.742, 0.0]
[-21.6278, 0.0]
[-21.5135, 0.0]
[-21.3993, 0.0]
[-21.285, 0.0]
[-21.1708, 0.0]
[-21.0565, 0.0]
[-20.9423, 0.0]
[-20.828, 0.0]
[-20.7137, 0.0]
[-20.5995, 0.0]
[-20.4852, 0.0]
[-20.371, 0.0]
[-20.2567, 0.0]
[-20.1425, 0.0]
[-20.0282, 0.0]
[-19.914, 0.0]
[-19.7

把每个列表添加到each_line[] 空列表里面，这样一个大列表含有许多小列表。

In [12]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
for i in all_data_dos:
	each_line=[]  #新建空的列表存放每一行的数据
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		lines = i.split("\n") #
		for line in lines:    #对每条线，每一个数据点进行迭代，一个大列表。
			each_line.append(list(map(float,line.split())))   #以空格的方法进行切割,这样就每个数据点切割成 能量和后面的状态数。#在用list(map(float,列表_含有字符串)) 转化成浮点数    
		print(each_line)  #前面的列表是第一条线，后面的列表是第二条线。已经把两条线的数据点已经切割开。
    

[[-26.655, 0.0], [-26.5407, 0.0], [-26.4264, 0.0], [-26.3122, 0.0], [-26.1979, 0.0], [-26.0837, 0.0], [-25.9694, 0.0], [-25.8552, 0.0], [-25.7409, 0.0], [-25.6267, 0.0], [-25.5124, 0.0], [-25.3982, 0.0], [-25.2839, 0.0], [-25.1697, 0.0], [-25.0554, 0.0], [-24.9411, 0.0], [-24.8269, 0.0], [-24.7126, 0.0], [-24.5984, 0.0001], [-24.4841, 0.0006], [-24.3699, 0.0006], [-24.2556, 0.001], [-24.1414, 0.0012], [-24.0271, 0.0014], [-23.9129, 0.0016], [-23.7986, 0.0016], [-23.6843, 0.0017], [-23.5701, 0.0017], [-23.4558, 0.0017], [-23.3416, 0.0017], [-23.2273, 0.0009], [-23.1131, 0.0002], [-22.9988, 0.0], [-22.8846, 0.0], [-22.7703, 0.0], [-22.6561, 0.0], [-22.5418, 0.0], [-22.4276, 0.0], [-22.3133, 0.0], [-22.199, 0.0], [-22.0848, 0.0], [-21.9705, 0.0], [-21.8563, 0.0], [-21.742, 0.0], [-21.6278, 0.0], [-21.5135, 0.0], [-21.3993, 0.0], [-21.285, 0.0], [-21.1708, 0.0], [-21.0565, 0.0], [-20.9423, 0.0], [-20.828, 0.0], [-20.7137, 0.0], [-20.5995, 0.0], [-20.4852, 0.0], [-20.371, 0.0], [-20.2567, 0

### 如何把两条线拼接出，两条线的能量合并在一起，第二列和第三列分别是它们的态密度。    
迭代的方式。把所有的eac_line 加到总列表里面。

In [13]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
all_lines = []   #建立一个总列表。
for i in all_data_dos:
	each_line=[]  #新建空的列表存放每一行的数据
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		lines = i.split("\n") #
		for line in lines:    #对每条线，每一个数据点进行迭代，一个大列表。
			each_line.append(list(map(float,line.split())))   #以空格的方法进行切割,这样就每个数据点切割成 能量和后面的状态数。#在用list(map(float,列表_含有字符串)) 转化成浮点数    
		all_lines.append(each_line)  #前面的列表是第一条线，后面的列表是第二条线。已经把两条线的数据点已经切割开。
#print(len(all_lines))
for i in all_lines[1:]:   #对all_lines 进行迭代 ,第二条线的第二列态密度移到第一条线第二列能量的右侧，变为上半部分的第三列。 all_lines[1:] 代表除了第一条线数据外，其它更多的线和数据
	for index in range(len(i)):
		all_lines[0][index].append(i[index][1])   #对应第一条线上的行index，i[index][1]第i条线的第二列dos数据。
print(all_lines[0])
	


[[-26.655, 0.0, 0.0], [-26.5407, 0.0, 0.0], [-26.4264, 0.0, 0.0], [-26.3122, 0.0, 0.0], [-26.1979, 0.0, 0.0], [-26.0837, 0.0, 0.0], [-25.9694, 0.0, 0.0], [-25.8552, 0.0, 0.0], [-25.7409, 0.0, 0.0], [-25.6267, 0.0, 0.0], [-25.5124, 0.0, 0.0], [-25.3982, 0.0, 0.0], [-25.2839, 0.0, 0.0], [-25.1697, 0.0, 0.0], [-25.0554, 0.0, 0.0], [-24.9411, 0.0, 0.0], [-24.8269, 0.0, 0.0], [-24.7126, 0.0, 0.0], [-24.5984, 0.0001, 0.0], [-24.4841, 0.0006, 0.0], [-24.3699, 0.0006, 0.0], [-24.2556, 0.001, 0.0], [-24.1414, 0.0012, 0.0], [-24.0271, 0.0014, 0.0], [-23.9129, 0.0016, 0.0], [-23.7986, 0.0016, 0.0], [-23.6843, 0.0017, 0.0], [-23.5701, 0.0017, 0.0], [-23.4558, 0.0017, 0.0], [-23.3416, 0.0017, 0.0], [-23.2273, 0.0009, 0.0], [-23.1131, 0.0002, 0.0], [-22.9988, 0.0, 0.0], [-22.8846, 0.0, 0.0], [-22.7703, 0.0, 0.0], [-22.6561, 0.0, 0.0], [-22.5418, 0.0, 0.0], [-22.4276, 0.0, 0.0], [-22.3133, 0.0, 0.0], [-22.199, 0.0, 0.0], [-22.0848, 0.0, 0.0], [-21.9705, 0.0, 0.0], [-21.8563, 0.0, 0.0], [-21.742, 0.0,

### 输出

In [16]:
file1 = open("new0.dat",'r')
all_data = file1.read()   
file1.seek(0)  #文件指针移到前面位置
all_data_lines = file1.readlines()
all_data_dos=all_data.split("\n\n") # print(all_data.split("\n"))只是把一行进行分割，我们需要前面一段和后面一段进行分割
all_lines = []   #建立一个总列表。
for i in all_data_dos:
	each_line=[]  #新建空的列表存放每一行的数据
	if i.strip("\n") != '':  # 最后空格还有换行符去掉，判断是不是空格，
		lines = i.split("\n") #
		for line in lines:    #对每条线，每一个数据点进行迭代，一个大列表。
			each_line.append(list(map(float,line.split())))   #以空格的方法进行切割,这样就每个数据点切割成 能量和后面的状态数。#在用list(map(float,列表_含有字符串)) 转化成浮点数    
		all_lines.append(each_line)  #前面的列表是第一条线，后面的列表是第二条线。已经把两条线的数据点已经切割开。
#print(len(all_lines))
for i in all_lines[1:]:   #对all_lines 进行迭代 ,第二条线的第二列态密度移到第一条线第二列能量的右侧，变为上半部分的第三列。 all_lines[1:] 代表除了第一条线数据外，其它更多的线和数据
	for index in range(len(i)):
		all_lines[0][index].append(i[index][1])   #对应第一条线上的行index，i[index][1]第i条线的第二列dos数据。
# 输出
with open("reform.dat",'w') as writer:   #对all_lines 每一行进行迭代，在把三个float值[-26.655, 0.0, 0.0]写在文件里
	for i in all_lines[0]:
		writer.write("%7.3f %7.3f %7.3f\n " %(i[0],i[1],i[2]))   #wirte方法只接受字符串，写的时候要写入字符串，采用格式替代的方法。带3位小数。 


In [19]:
import numpy as np
new_data = np.array(all_lines[0])
print(new_data)

[[-2.66550e+01  0.00000e+00  0.00000e+00]
 [-2.65407e+01  0.00000e+00  0.00000e+00]
 [-2.64264e+01  0.00000e+00  0.00000e+00]
 [-2.63122e+01  0.00000e+00  0.00000e+00]
 [-2.61979e+01  0.00000e+00  0.00000e+00]
 [-2.60837e+01  0.00000e+00  0.00000e+00]
 [-2.59694e+01  0.00000e+00  0.00000e+00]
 [-2.58552e+01  0.00000e+00  0.00000e+00]
 [-2.57409e+01  0.00000e+00  0.00000e+00]
 [-2.56267e+01  0.00000e+00  0.00000e+00]
 [-2.55124e+01  0.00000e+00  0.00000e+00]
 [-2.53982e+01  0.00000e+00  0.00000e+00]
 [-2.52839e+01  0.00000e+00  0.00000e+00]
 [-2.51697e+01  0.00000e+00  0.00000e+00]
 [-2.50554e+01  0.00000e+00  0.00000e+00]
 [-2.49411e+01  0.00000e+00  0.00000e+00]
 [-2.48269e+01  0.00000e+00  0.00000e+00]
 [-2.47126e+01  0.00000e+00  0.00000e+00]
 [-2.45984e+01  1.00000e-04  0.00000e+00]
 [-2.44841e+01  6.00000e-04  0.00000e+00]
 [-2.43699e+01  6.00000e-04  0.00000e+00]
 [-2.42556e+01  1.00000e-03  0.00000e+00]
 [-2.41414e+01  1.20000e-03  0.00000e+00]
 [-2.40271e+01  1.40000e-03  0.000

## d-band center(d带中心)

In [24]:
import numpy as np
new_data = np.array(all_lines[0])
energy = new_data[:,0]   #所有能量位于第一列
state = new_data[:,2]   
fenzi = np.trapz(energy*state,energy)   #trapz 矩形积方法，括号里第一个是y，第二个是x
fenmu = np.trapz(state,energy)
d_band = fenzi/float(fenmu)
print(d_band)


-1.858157958997648
